Ptw/stage 2 verify (#2)
* Run vendoring with versioned deps

* Move dependencies to 3rd-party

anticipating build file for this

* Verify `cargo build --offline` still works

* Add 3rd-party build file

But running into visibility issues!
```
ERROR: /Users/preston/git/bazel-rust-guided-experiment/stage-2-verify/3rd-party/BUILD.bazel:6:14: no such target '//backend:Cargo.toml': target 'Cargo.toml' not declared in package 'backend'; however, a source file of this name exists.  (Perhaps add 'exports_files(["Cargo.toml"])' to backend/BUILD?) defined by /Users/preston/git/bazel-rust-guided-experiment/stage-2-verify/backend/BUILD.bazel and referenced by '//3rd-party:crates_vendor'
```

* Export file

but this runs into
```
bazel run //3rd-party:crates_vendor
Error: Failed to parse label from string: @__main__//3rd-party/crates/wasi-0.11.0+wasi-snapshot-preview1:BUILD.bazel
```
so pin specific tokio version

* Update cargo lock

now that we are running offline

* Move to vendored versions of dependency rules

Sinces these things are unneeded now!