Ptw/stage 2 (#1)
* Copy from stage1 to stage 2

* Attempt vendoring dependencies

https://bazelbuild.github.io/rules_rust/crate_universe.html#crates_vendor
isn't too clear on steps to cover---I don't want to list out dependencies manually.
Instead, we look to https://github.com/bazelbuild/rules_rust/blob/0265c293f195a59da45f83aafcfca78eaf43a4c5/examples/crate_universe/vendor_local_manifests/BUILD.bazel
to see what to do.

However, trying to copy
https://github.com/bazelbuild/rules_rust/blob/0265c293f195a59da45f83aafcfca78eaf43a4c5/examples/crate_universe/vendor_local_manifests/BUILD.bazel#L1
leads to `vendor` is not a package.
For that reason, we keep around the old
`all_crate_deps` while we try to vendor.

* Upgrade to 0.4.0

And update lockfile

* Pin specific version

From https://github.com/bazelbuild/rules_rust/blob/0265c293f195a59da45f83aafcfca78eaf43a4c5/examples/crate_universe/vendor_local_manifests/Cargo.toml#L8

And make BUILD so it only includes vendor target.
This works if we have the vendor_path just be vendor,
but it places it inside of backend. We want it at the
root level. :/

* Specify full path

* Run `cargo vendor --versioned-dirs`

Should have done this originally

* Specify relative path that works

Not sure if doing this or 3rd-party like in
https://bazelbuild.github.io/rules_rust/crate_universe.html#crates_vendor
would be better.

Note that this adds some meta build files
and build files for all of the dependencies!

* Add alternate approach as a note

* Try loading from vendor instead

But running into
```
ERROR: /Users/preston/git/bazel-rust-guided-experiment/stage-2-crates-vendor/backend/BUILD.bazel:13:12: //backend:hello_world: invalid label '//backend/../vendor/axum-0.5.6:axum' in element 0 of attribute 'deps' in 'rust_binary' rule: invalid package name 'backend/../vendor/axum-0.5.6': package name component contains only '.' characters
```
so looks like relative path didn't actually work...

Looks like it's time to work on 3rd-party!

* Separate vendoring out into another buildfile

Running into permissions issues:
```
bazel run //3rd-party:crates_vendor

ERROR: /Users/preston/git/bazel-rust-guided-experiment/stage-2-crates-vendor/3rd-party/BUILD.bazel:6:14: no such target '//:Cargo.toml': target 'Cargo.toml' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["Cargo.toml"])' to /BUILD?)
```

* Correct surrounding build and workspace files

to run
```
CARGO_BAZEL_REPIN=true bazel run //3rd-party:crates_vendor
```

And remove vendor directory

* Revert to using local deps

Now that 3rd-party has succeeded

* Verify that `cargo build --offline` still works

Needed to change this config, but now it does!